[package]
name = "veus"
version = "0.1.0"
authors = ["Matheus D. Gudergues <matheus.gudergues@skyboxlabs.com>"]
edition = "2018"

[dependencies]
vulkano = "0.11.1"
winit = "0.18.0"
vulkano-win = "0.11.1"
